name: Code Quality & Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript Check
        run: npx tsc --noEmit

      - name: Run auto-fix (format + lint)
        run: |
          npm run format
          npm run lint:fix

      - name: Commit & Create Pull Request for Auto-Fixes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: auto-fix formatting and linting"
          branch: "chore/autofix"
          title: "chore: auto-fix formatting and linting"
          body: |
            This pull request contains automatic formatting and linting fixes
            applied by GitHub Actions.
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          signoff: false

      - name: Final quality checks (strict)
        run: |
          npm run format:check
          npm run lint -- --max-warnings 0
          npx tsc --noEmit
