# code-quality.yml
name: Code Quality & Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Check ESLint (including import sorting)
        run: npm run lint -- --max-warnings 0

      - name: TypeScript compilation check
        run: npx tsc --noEmit
